controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\db\Query;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                   // 'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        
         return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        //die("dd");
       

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            //return $this->goBack();
            //return $this->redirect('/web/admin');
            return $this->redirect('/web/');

        }else{

             if (Yii::$app->user->isGuest) {
                 return $this->render('login', [
                    'model' => $model,
                ]);
                //die("ff22");
            //return $this->redirect(Yii::$app->user->loginUrl);
            }else{
                return $this->redirect('/web/');
            }
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionIniciarsesion()
    {
        //die("dd");
       

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            //return $this->goBack();
            //return $this->redirect('/web/admin');
            return $this->redirect('/web/');

        }else{

             if (Yii::$app->user->isGuest) {
                 return $this->render('iniciarsesion', [
                    'model' => $model,
                ]);
                //die("ff22");
            //return $this->redirect(Yii::$app->user->loginUrl);
            }else{
                return $this->redirect('/web/');
            }
        }

        return $this->render('iniciarsesion', [
            'model' => $model,
        ]);
    }

     public function actionFindidentity(){
        $connection = \Yii::$app->db;     
        $model = $connection->createCommand("SELECT * FROM clientes where codigo=".$_POST['cedula']);
        $users = $model->queryOne();
        //var_dump($users);
        if ($users)
        {
            return 1;
        }else{
            return 0;
        } 
        
        //return $this->render('findidentity');
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->redirect(Yii::$app->user->loginUrl);
    }

    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            // change layout for error action
            if ($action->id == 'login')
                $this->layout = 'login';
            return true;
        } else {
            return false;
        }
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionDescargas()
    {
        return $this->render('descargas');
    }

    public function actionConvenios()
    {
        return $this->render('convenios');
    }

    public function actionMision()
    {
        return $this->render('mision');
    }

    public function actionVision()
    {
        return $this->render('vision');
    }

    public function actionMargenutilidades()
    {
        return $this->render('margenutilidades');
    }

    public function actionParticipes()
    {
        return $this->render('participes');
    }

    public function actionEducacionfinanciera()
    {
        return $this->render('educacionfinanciera');
    }

        public function actionCesantia()
    {
        $model = new ContactForm();
       
           // Yii::$app->session->setFlash('contactFormSubmitted');

            //return $this->refresh();
       
        return $this->render('cesantia', [
            'model' => $model,
        ]);
    }

 

    /**
     * Displays Consulta cupon cedula.
     *
     * @return string
     */
    public function actionConsultacuponcodigo()
    {
        $result = array();
        $return['status'] = false;
        if (!empty($_POST['param'])) {
            $tabla = 'opd_coupon_transaction_zombies';
            $return['status'] = true;
            $return['data'] = true;
            $arr_result = array();
            $arr_result_land = array();

            $query = new Query();
            $query->select('id, coupon_number,local_code_emission,terminal_code,ticket,status,creation_date')
                ->from($tabla . ' as a')
                ->where('coupon_number = ' . $_POST['param']);
            $command = $query->createCommand();
            $data = $command->queryAll();

            if ($data) {
                foreach ($data as $item) {
                    $arr_result['coupon_number'] = $item['coupon_number'];
                    $arr_result['local_code_emission'] = $item['local_code_emission'];
                    $arr_result['terminal_code'] = $item['terminal_code'];
                    $arr_result['ticket'] = $item['ticket'];
                    $arr_result['status'] = $item['status'];
                    $arr_result['creation_date'] = $item['creation_date'];
                }

                $query = new Query();
                $query->select('a.identity, a.codigo, a.sucursal, a.caja, a.ticket, a.num_tajeta_mas, a.tiene_si_no, a.date_create, b.name, b.lastname, b.email, b.province,p.description, b.city, b.address, b.phone, b.creation_date, b.birthdate, b.cellphone, b.gender, b.tarjetamas, b.terminos')
                    ->from('user_zombie_ticket_2017 as a')
                    ->innerJoin('user_zombies_2017 as b', 'a.identity = b.identity')
                    ->innerJoin('province as p', 'b.province = p.id')
                    ->where("a.codigo = '" . $_POST['param'] . "'")
                    ->groupBy('a.codigo');
                $command = $query->createCommand();
                //echo $command->getRawSql();
                //die();
                $data_landing = $command->queryAll();

                if ($data_landing) {
                    foreach ($data_landing as $item) {
                        $arr_result_land['identity'] = $item['identity'];
                        $arr_result_land['codigo'] = $item['codigo'];
                        $arr_result_land['sucursal'] = $item['sucursal'];
                        $arr_result_land['caja'] = $item['caja'];
                        $arr_result_land['ticket'] = $item['ticket'];
                        $arr_result_land['num_tajeta_mas'] = $item['num_tajeta_mas'];
                        $arr_result_land['tiene_si_no'] = $item['tiene_si_no'];
                        //$arr_result_land['date_create'] = $item['date_create'];
                        $arr_result_land['name'] = $item['name'];
                        $arr_result_land['lastname'] = $item['lastname'];
                        $arr_result_land['email'] = $item['email'];
                        $arr_result_land['province'] = $item['province'];
                        $arr_result_land['description'] = $item['description'];
                        $arr_result_land['city'] = $item['city'];
                        $arr_result_land['address'] = $item['address'];
                        $arr_result_land['phone'] = $item['phone'];
                        $arr_result_land['creation_date'] = $item['creation_date'];
                        $arr_result_land['birthdate'] = $item['birthdate'];
                        $arr_result_land['cellphone'] = $item['cellphone'];
                        $arr_result_land['gender'] = $item['gender'];
                        $arr_result_land['tarjetamas'] = $item['tarjetamas'];
                        $arr_result_land['terminos'] = $item['terminos'];
                    }
                    $return['status_landing'] = true;
                } else {
                    $return['status_landing'] = false;
                }
                $return['status_integracion'] = true;
                $return['base_integracion'] = $arr_result;
                $return['base_landing'] = $arr_result_land;
                $return['status'] = true;
            } else {
                $return['status_integracion'] = false;
                $return['status_landing'] = false;
                $return['base_integracion'] = $arr_result;

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * UserController class_implements(class)s the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index'],
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */


    /**
     * Displays a single User model.
     * @param string $id
     * @return mixed
     */
    public function actionIndex()
    {

        $id=Yii::$app->user->identity->id;
        $model = $this->findModel($id);
             if ($model->load(Yii::$app->request->post()) && $model->save()) {
                Yii::$app->getSession()->setFlash('success','Felicidades tus datos han sido guardados con éxito.');
                return $this->goHome();
        } 

        return $this->render('index', [
            'model' => $model,
        ]);
    }
    public function actionRegistro()
    {
//        return $this->redirect(array('/index', ['info' => '1']));
        //header('Location: /asoprep/index.php?info=1');
        //exit(0);

        $model = New User;
        $model->status_client="ACTIVE";
        $model->type_client="CLIENT";
       // $model->province_residence="PRUEBA";
        if (Yii::$app->request->post()){
          $formulario=Yii::$app->request->post();
          $province_residence=strtoupper($formulario['User']['province_residence']);
          $canton_residence=strtoupper($formulario['User']['canton_residence']);
          $zone_residence=strtoupper($formulario['User']['zone_residence']);
          $city_residence=strtoupper($formulario['User']['city_residence']);
        }
                // if($email){
                //     Yii::$app->getSession()->setFlash('success','No te olvides de revisar en la bandeja de spam.');
                // }
                // else{
                //     Yii::$app->getSession()->setFlash('warning','Un error ha ocurrido por favor contactate con soporte técnico.');
                // }

        //var_dump($formulario['User']);
//&& $model->save()
             if ($model->load(Yii::$app->request->post())) {
                $model->province_residence=$province_residence;
                $model->city_residence=$city_residence;
                $model->canton_residence=$canton_residence;
                $model->zone_residence=$zone_residence;
                $length = 10;
                $chars = array_merge(range(0,9), range('a','z'), range('A','Z'));
                shuffle($chars);
                $password = implode(array_slice($chars, 0, $length));
                $token=Yii::$app->getSecurity()->generateRandomKey();
                //$token= Yii::$app->getSecurity()->generatePasswordHash($token);
                //$user=$model->find();
                // /$user= User::findOne($model->identity);
                //$token= User::generatePasswordResetToken();
                
                //$user=$model->find();
                //$user->generatePasswordResetToken();
                $user=$model->find();
                //echo 'dededed'.$token;
                 //$model->password_reset_token;
                //$hash = Yii::$app->getSecurity()->generatePasswordHash($password);

                 //echo $user;

                  $usuario = (new \yii\db\Query())
                         ->select(['auth_key'])
                         ->from('user')
                         ->where(['identity' => $model->identity])
                         ->all();

                //$model->password=$password;
               
                        //$cont=0;
                        //echo var_dump($rowpremios);
                        /*foreach($rowpremios as $k => $premios){
                            $cont=1;
                           $return['premios'][$k]=$rowpremios[$k]['icon'];
                        }*/
                    // echo   $user->password_reset_token();
                       // echo var_dump($usuario);
                    if ($usuario)
                    {
                         Yii::$app->getSession()->setFlash('success','El usuario ya exite.');
                         $info=1;
                        return $this->redirect(['site/index','info' => 2]);
                    }else
                    {
                          if ($model->save()) {
                           // echo @$usuario[0]['auth_key'];

                        $usuario = (new \yii\db\Query())
                         ->select(['auth_key'])
                         ->from('user')
                         ->where(['identity' => $model->identity])
                         ->all();      

                      // echo var_dump($model);
                      $name=$model->names;
                      $email=  Yii::$app->mailer->compose('reset', [
                      'names' => $name,
                      'url' => Yii::$app->urlManager->createAbsoluteUrl(['site/newuser','url'=>@$usuario[0]['auth_key']])
                      ])->setFrom('info@asopreol.com')
                      ->setTo($model->username)
                      ->setSubject($name." "."Información Asopreol")
                     ->send();
                            $info=1;
                            Yii::$app->getSession()->setFlash('success','Felicidades tus datos han sido guardados con éxito.');
                            //return $this->goHome();
                            //return $this->render('index', [
                             //   'info' => $info,
                            //]);
                            //return $this->render('/site/index',['model'=>$model,'info'=>$info]);
                           return $this->redirect(['site/index','info' => 1]);
                       }

                    }

               
       
        } 

        return $this->render('registro', [
            'model' => $model,
        ]);
    }






    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */




    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/layouts/login.php
<?php
use yii\helpers\Html;
use app\assets\AppAsset;
use app\themes\adminLTE\assets\AdminlteAsset;
/* @var $this \yii\web\View */
/* @var $content string */

AdminlteAsset::register($this);
AppAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

  <?php $this->beginBody() ?>
      <?php echo $content; ?>
  <?php $this->endBody() ?>

</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\helpers\Url;
use app\models\Section;
AppAsset::register($this);
$sections=Section::find()->where(['status'=>'ACTIVE','section_id'=>NULL])->all();

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
<meta name="title" content="Crear | Unidad Educativa Crear.">
<meta name="description" content="Unidad Educativa Crear.">
<meta name="google" content="">
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

    <div id="cont-general">
        <header class="container-fluid pos-relative">
        <div style="width: 100%; text-align: center;">
          <a href="<?= URL::base() ?>"><img src="<?= URL::base() ?>/images/site/logo_crear.svg" alt="Crear" class="img-logo-asoprep" style="width: 15%;padding-top: 10px;padding-left: 4%; text-align: center; float: none;"></a>
        </div>

            <!-- -->
            <nav class="navbar navbar-default" role="navigation" style="position: initial;">
              <!-- El logotipo y el icono que despliega el menú se agrupan
                   para mostrarlos mejor en los dispositivos móviles -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target=".navbar-ex1-collapse">
                  <span class="sr-only">Desplegar navegación</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
              </div>
             
              <!-- Agrupar los enlaces de navegación, los formularios y cualquier
                   otro elemento que se pueda ocultar al minimizar la barra -->
              <div class="collapse navbar-collapse navbar-ex1-collapse container">
                <ul class="nav navbar-nav" style="float:initial">
                    <li style=" "><a href="<?= URL::base() ?>/">INICIO</a></li>

                <?php foreach($sections as $section): ?>
                       <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?= $section->title ?><b class="caret"></b></a>
                        <ul class="dropdown-menu">
                        <?php foreach($section->sections as $subsection): ?>

                            <?php
                            $link="#";
                            if($subsection->description){
                             $pos = strpos($subsection->description,"http");
                             $pos2 = strpos($subsection->description,"https");
                              //echo strpos($subsection->description,"http");
                             $target="";
                             if ($pos !== false || $pos2 !== false){
                                $link=$subsection->description; 
                                $target='target="_blank"';
                             }else{
                                $target="";
                                $link=URL::base().$subsection->description; 
                             }
                            }else{
                                foreach($subsection->contents as $contents){
                                    $link=Url::to(['site/content','id'=>$contents->id]);
                                    break;
                                }
                            }
                            
                             ?>
                             <?php if ($subsection->description=='http://www.crear.edu.ec/'){ $link='http://www.crear.edu.ec/'; } ?>
                          <li><a <?=@$target?> href="<?= $link ?>"><?= $subsection->title ?></a>
                            <ul><li></li></ul>
                          </li>
                          <li class="divider"></li>
                        <?php endforeach; ?>
                        </ul>
                      </li>
                  <?php endforeach; ?>
                  <li><a href="<?= Url::to(['site/contact']) ?>">CONTÁCTENOS</a></li> 
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">CUENTA<b class="caret"></b></a>
                    <ul class="dropdown-menu"> 
                       <?php if(Yii::$app->user->isGuest){ ?>
                          <li style=" "><a href="<?= Url::to(['user/registro']) ?>">Regístrate</a></li>
                          <li class="divider"></li>
                          <li style=" "><a href="<?= Url::to(['site/iniciarsesion']) ?>">Iniciar Sesión</a></li>
                      <?php }else{ ?>
                         <li style=" "><a href="<?= Url::to(['site/logout']) ?>">Cerrar Sesión (<?= Yii::$app->user->identity->names ?>)</a></li>
                         <li class="divider"></li>
                        <!-- <li style=" "><a href="<?= Url::to(['user/index']) ?>"><?= Yii::$app->user->identity->names ?></a></li>-->
                      <?php } ?>   

                    </ul>
                    
                               
                </ul>
              </div>
            </nav>
            <!-- -->
        </header>

        <?= $content ?>
     
        <footer class="container-fluid background-footer">
            <div class="container">
                <div class="col-md-15 col-sm-3 text-center">
                    <h1>CREAR</h1>
                    <a href="<?= URL::base() ?>/">Misión</a>
                    <a href="<?= URL::base() ?>/">Visión</a>
                    <h1>EDUCACIÓN</h1>
                    <a href="<?= URL::base() ?>/">Maternal</a>
                    <a href="<?= URL::base() ?>/">Educación Inicial</a>
                    <a href="<?= URL::base() ?>/">Ciclo Básico</a>
                    <a href="<?= URL::base() ?>/">Bachillerato</a>
                </div>
                <div class="col-md-15 col-sm-3 text-center">
                    <h1>ACTIVIDADES</h1>
                    <a href="<?= URL::base() ?>/pagina/manejando_tu_dinero.pdf">Noticias</a>
                    <a href="<?= URL::base() ?>/pagina/manejando_tu_dinero.pdf">Eventos</a>
                    <h1>ADMISIONES</h1>
                    <a href="<?= URL::base() ?>/">Periodo Lectivo 2018 - 2019</a>
                    <a href="<?= URL::base() ?>/">Requisitos</a>
                </div>
                <div class="col-md-15 col-sm-3 text-center">
                    <h1>SÍGUENOS EN:</h1>
                    <div style="text-align: left;">
                      <a href="https://www.facebook.com/ue.crear" style="float: none;">
                        <img class="redes-sociales" src="<?= URL::base() ?>/images/site/facebook.fw.png">
                      </a>&nbsp;&nbsp;
                      <a href="https://twitter.com/unidadeducati20" style="float: none;">
                        <img class="redes-sociales" src="<?= URL::base() ?>/images/site/twitter.fw.png">
                      </a>&nbsp;&nbsp;
                      <a href="https://www.instagram.com/ue.crear" style="float: none;">
                        <img class="redes-sociales" src="<?= URL::base() ?>/images/site/instagram.fw.png">
                      </a>
                    </div>
                    <h1>CONTÁCTANOS</h1>
                    <a href="" style="">Km. 2 1/2 Vía Samborodón, Urb. Tornero III, Calle Santa María #235.</a>
                    <a href="#"><span style="font-weight: bold;">Teléfono:</span> (04) 2831023 - 2835215 - 2835216</a>
 
                    
                </div>
            </div>
            
        </footer>
        <div class="container-fluid" style="background-color: white; font-family: 'roboto-light'; text-align: center;color: #1A185C; padding: 1%; font-size: 11px; font-weight: bold;">
                2018 CREAR. Todos los derechos reservados.
            </div>
    </div>



<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main2.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'FIRE',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; ADFIRE <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main3.php
<?php
use yii\helpers\Html;
use yii\web\view;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\helpers\Url;
/* @var $this \yii\web\View */
/* @var $content string */
$script=<<< JS
 

JS;
$this->registerJs($script,View::POS_END);
AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" ng-app="contigo">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="<?= URL::base() ?>/images/favicon.ico" type="image/x-icon">
    <link rel="icon" href="<?= URL::base() ?>/images/favicon.ico" type="image/x-icon">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <script src="<?= URL::base() ?>/js/jquery-1.12.3.min.js"></script>
    <script src="<?= URL::base() ?>/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.0/angular.min.js"></script>
</head>
<?php if(isset(Yii::$app->view->params['body'])){ ?>
<body id="<?= Yii::$app->view->params['body'] ?>">
<?php }else{ ?>
<body>
<?php } ?>
<?php $this->beginBody() ?>
<script type="text/javascript">
var contigo = angular.module('contigo', []);
contigo.controller('CarController', function CarController($scope, $rootScope, $window, $http, $location, $element) {
  $scope.car = [];
  $scope.n = 0;
  init();
  $rootScope.$on('addCar', function (event, data) {
    // 'Emit!'
    $scope.car = data;
    $scope.n = ($scope.car)?$scope.car.length:0;
  });
  function init(){
    $scope.car = (localStorage.getItem('cotizacion'))?JSON.parse(localStorage.getItem('cotizacion')):null;
    $scope.n = ($scope.car)?$scope.car.length:0;
  }

});
</script>
<header>
   

</header>

<?= $content; ?>
<!--<footer class="container-fluid text-center">
® <?= date('Y') ?> Continental.   Todos los Derechos Reservados.    Desarrollado por SHARE DIGITAL AGENCY
</footer>-->
<?php $this->endBody() ?>
<div id="menu-principal">
<?= $this->render('@app/views/site/index.php') ?>
</div>
</body>
</html>
<?php $this->endPage() ?>